/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTracesIndexRouteImport } from './routes/api/traces/index'
import { Route as ApiJobsIndexRouteImport } from './routes/api/jobs/index'
import { Route as ApiTracesIdRouteImport } from './routes/api/traces/$id'
import { Route as ApiJobsStatsRouteImport } from './routes/api/jobs/stats'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTracesIndexRoute = ApiTracesIndexRouteImport.update({
  id: '/api/traces/',
  path: '/api/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIndexRoute = ApiJobsIndexRouteImport.update({
  id: '/api/jobs/',
  path: '/api/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTracesIdRoute = ApiTracesIdRouteImport.update({
  id: '/api/traces/$id',
  path: '/api/traces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsStatsRoute = ApiJobsStatsRouteImport.update({
  id: '/api/jobs/stats',
  path: '/api/jobs/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/api/jobs/$id',
  path: '/api/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/traces': typeof TracesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/jobs/stats': typeof ApiJobsStatsRoute
  '/api/traces/$id': typeof ApiTracesIdRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/traces/': typeof ApiTracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/traces': typeof TracesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/jobs/stats': typeof ApiJobsStatsRoute
  '/api/traces/$id': typeof ApiTracesIdRoute
  '/api/jobs': typeof ApiJobsIndexRoute
  '/api/traces': typeof ApiTracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/traces': typeof TracesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/jobs/stats': typeof ApiJobsStatsRoute
  '/api/traces/$id': typeof ApiTracesIdRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/traces/': typeof ApiTracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/traces'
    | '/api/auth/$'
    | '/api/jobs/$id'
    | '/api/jobs/stats'
    | '/api/traces/$id'
    | '/api/jobs/'
    | '/api/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/traces'
    | '/api/auth/$'
    | '/api/jobs/$id'
    | '/api/jobs/stats'
    | '/api/traces/$id'
    | '/api/jobs'
    | '/api/traces'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/traces'
    | '/api/auth/$'
    | '/api/jobs/$id'
    | '/api/jobs/stats'
    | '/api/traces/$id'
    | '/api/jobs/'
    | '/api/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  TracesRoute: typeof TracesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiJobsIdRoute: typeof ApiJobsIdRoute
  ApiJobsStatsRoute: typeof ApiJobsStatsRoute
  ApiTracesIdRoute: typeof ApiTracesIdRoute
  ApiJobsIndexRoute: typeof ApiJobsIndexRoute
  ApiTracesIndexRoute: typeof ApiTracesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/traces/': {
      id: '/api/traces/'
      path: '/api/traces'
      fullPath: '/api/traces/'
      preLoaderRoute: typeof ApiTracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/': {
      id: '/api/jobs/'
      path: '/api/jobs'
      fullPath: '/api/jobs/'
      preLoaderRoute: typeof ApiJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/traces/$id': {
      id: '/api/traces/$id'
      path: '/api/traces/$id'
      fullPath: '/api/traces/$id'
      preLoaderRoute: typeof ApiTracesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/stats': {
      id: '/api/jobs/stats'
      path: '/api/jobs/stats'
      fullPath: '/api/jobs/stats'
      preLoaderRoute: typeof ApiJobsStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/api/jobs/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  TracesRoute: TracesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiJobsIdRoute: ApiJobsIdRoute,
  ApiJobsStatsRoute: ApiJobsStatsRoute,
  ApiTracesIdRoute: ApiTracesIdRoute,
  ApiJobsIndexRoute: ApiJobsIndexRoute,
  ApiTracesIndexRoute: ApiTracesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
